services:
  - type: web
    name: emotion-detection-babalola
    env: python
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app -w 1 --timeout 120
    plan: free
